name: Post updates to X
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [ closed ]
    branches: [ "main", "master" ]
  issues:
    types: [ opened ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      start:
        description: 'Start commit SHA (optional)'
        required: false
      end:
        description: 'End commit SHA (optional)'
        required: false
jobs:
  promo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      packages: read
      pull-requests: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create temporary Maven POM for CI
        run: |
          mkdir -p ci-maven
          cat > ci-maven/pom.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.sigwarth</groupId>
              <artifactId>music-machine-ci</artifactId>
              <version>0.0.1-SNAPSHOT</version>
              <packaging>pom</packaging>
              <name>Music Machine CI Placeholder</name>
              <description>Ephemeral placeholder POM for CI; not part of the repo.</description>
          </project>
          EOF
      - name: Set up JDK and GitHub Packages for Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          cache: maven
          cache-dependency-path: ci-maven/pom.xml
      - name: Run Promo Bot
        uses: theoliverlear/Sigwarth-Software-Suite@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          app_name: "Music Machine"
          mode: prod
          start:           ${{ github.event.inputs.start }}
          end:             ${{ github.event.inputs.end }}
          openai_key:      ${{ secrets.OPENAI_KEY }}
          github_token:    ${{ secrets.GITHUB_TOKEN }}
          x_api_key:       ${{ secrets.X_API_KEY }}
          x_secret:        ${{ secrets.X_SECRET }}
          x_access_token:  ${{ secrets.X_ACCESS_TOKEN }}
          x_access_secret: ${{ secrets.X_ACCESS_SECRET }}
          repo_name:       ${{ secrets.REPO_NAME }}
      - name: Clean up temporary POM
        if: always()
        run: rm -rf ci-maven